name: farmasi-app

services:
  farmasi-app:
    image: ghcr.io/mentionabbe-wq/farmasi-app:latest
    container_name: farmasi-app
    ports:
      - "3000:3000"
    volumes:
      - farmasi-data:/app/data
      - farmasi-uploads:/app/uploads
    environment:
      - PORT=3000
      - DATA_DIR=/app/data
      - UPLOAD_DIR=/app/uploads
    restart: unless-stopped

volumes:
  farmasi-data:
  farmasi-uploads:
